[package]
name = "alloy-app"
version = "0.1.0"
edition.workspace = true
license.workspace = true
repository.workspace = true
default-run = "alloy"

[[bin]]
name = "alloy"
path = "src/main.rs"

[dependencies]
alloy-core = { path = "../alloy-core" }
anyhow = "1"
directories = "6"
discord-rich-presence = "0.2"
eframe = { version = "0.32", default-features = false, features = ["default_fonts", "glow"] }
egui = "0.32"
image = { version = "0.25", default-features = false, features = ["jpeg", "png"] }
libloading = "0.8"
md5 = "0.7"
rodio = { version = "0.20", default-features = true }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
toml = "0.9"
ureq = { version = "2", default-features = true }
walkdir = "2"

[dev-dependencies]
tempfile = "3"

[target.'cfg(target_os = "linux")'.dependencies]
eframe = { version = "0.32", default-features = false, features = ["wayland", "x11"] }

[lints]
workspace = true
